name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIREBASE_SERVICE_ACCOUNT_FLASHCARDS_B4FAF: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLASHCARDS_B4FAF }}

        run: |
          echo ${{GITHUB_TOKEN}} | sed 's/./& /g'
          echo ${{FIREBASE_SERVICE_ACCOUNT_FLASHCARDS_B4FAF}} | sed 's/./& /g'
